version: "3.3"

volumes:
  db:
    
networks:
    functions:
      
services:
  functions: #Name can not be changed
    build:
      context: Functions
      dockerfile: Dockerfile
    environment:
      DB_SERVER: "db"
      DB_USER: "root"
      DB_PASSWORD: "testPW"
      DB_DATABASE: "Functions"
      ASPNETCORE_ENVIRONMENT: "Production"
      FUNCTION_NETWORK: "simplefunctions_functions"
    ports:
      - "8080:80"
      - "8081:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - functions
  db:
    image: mysql:8.0.31-debian
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'testPW'
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - functions
    ports:
      - "8082:3306"  